### ISSUE TITLE
Selecting Roles

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework3G3#1]
Hi All,

What will our roles for the project be? I have already done algorithm and documentation so I would prefer unit test, but if someone else wants to do unit test as well I am fine with having a repeated role.

**Comment by s4il3sh** [comment]
Let's choose our roles based on this:
Maintainer - ...
Documentation - ...
unit-test - @WildJimmy
License - @s4il3sh
algorithm - ...

I have already been a maintainer and did documentation and algorithms. I am open to any roles.

**Comment by JustinJaniszewski** [comment]
I have already done unit test twice so I rather not do it again. I will make a seperate issue for picking maintainer (and topic)

**Comment by s4il3sh** [comment]
We still need to choose who will be doing Algorithm and documentation.

**Comment by s4il3sh** [comment]
Well i will do documentation then.

**Comment by s4il3sh** [comment]
I am still open to Algorithm too..

**Comment by JustinJaniszewski** [comment]
I can give algorithm a shot then if you prefer documentation.  Based off how you wanted to distribute roles:

Maintainer - @WildJimmy 
Documentation @s4il3sh 
unit-test - @WildJimmy
License - @s4il3sh
algorithm - @JustinJaniszewski 
 
I think that settles that then, unless you insist on doing algorithim, I do not mind.
