### ISSUE TITLE
Classical Mechanical Functions

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework3G3#14]
What can be the better option for any Classical mechanical functions to implement in this homework?

**Comment by JustinJaniszewski** [comment]
If its not already taken, you could possibly calculate the force of gravity from 1 object on another object using (F=Gm1m2)/r^2

**Comment by s4il3sh** [comment]
Or you can determine the moment of inertia of a body.

**Comment by reshnashrestha** [comment]
@s4il3sh Thank you for suggestion, we did projectile motion with air resistance.
