### ISSUE TITLE
Who will be maintainer?

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework3G3#3]
I have been it once already and I think we should priortize someone if they haven't been that role yet.

**Comment by WildJimmy** [comment]
I've been a maintainer as well, but I don't mind doing it again if one of us has to. If either of you would prefer that's fine but otherwise I can do it

**Comment by JustinJaniszewski** [comment]
I feel the same way as Jimmy.  @s4il3sh if you would like to be the maintainer you can be. Otherwise, I am fine with Jimmy being the maintainer. Your decision.

**Comment by s4il3sh** [comment]
Well. I am OK with this decision. Let's go.
