### ISSUE TITLE
Added some lines to the python files

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework3G3#31]
Added some of the actual data of the experiment inside the code. Please take a look at it.

**Comment by WildJimmy** [comment]
@s4il3sh Looks good. This is different values for m and x for a given k, correct? So if we know k and one of these we could predict another? Let me know if that interpretation is wrong

**Comment by s4il3sh** [comment]
Actually, with those data, we will find best-fit values - from the slope and find the spring constant.

**Comment by s4il3sh** [comment]
I guess we add things in our code too to predict values after we determine best-fit values for the spring constant.

**Comment by s4il3sh** [comment]
The code is still not complete though, I have just added the experimental values. More things to do in the coding.
