### ISSUE TITLE
Not able to Label

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework3G3#34]
Hi,
 I am not able to create label while creating the issue. What might be the problem there?

**Comment by WildJimmy** [comment]
@pratibha77118 I think you can only assign labels if you're a member of the group. Are you able to assign labels in your own group?

**Comment by tirthbha** [comment]
@pratibha77118 Yeah, creating a label is only a part of maintainer.

**Comment by pratibha77118** [comment]
@WildJimmy I am not able to assign labels in my own group.    I am in doubt whether I did it correctly. Each time I click on label I am directed to already labelled issues. What should I do to label my own issue?

**Comment by s4il3sh** [comment]
@pratibha77118 did you check at the bottom after you click the label - there you will find the edit labels button. Also, to do this you should be a maintainer first. If you are a maintainer, you will see the edit labels button.
