### ISSUE TITLE
What topic should we do?

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework3G3#4]
We must pick something from classical mechanics. Keep in mind Group 2 has already chosen 1D elastic collision.

**Comment by s4il3sh** [comment]
how about determining the spring constant or Young's modulus of a material?

**Comment by JustinJaniszewski** [comment]
Alright, I will let other groups know.

**Comment by s4il3sh** [comment]
OK. Who will be doing Algorithm?

**Comment by JustinJaniszewski** [comment]
That is discussed in #1.
