### ISSUE TITLE
Algorithm Milestone

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework3G3#42]
@JustinJaniszewski Are we good? I am still wondering about the code. I need to work on documentation and docstring after the code is available. I would like to know if any problem persists, we could discuss and move forward with our coding!

**Comment by JustinJaniszewski** [comment]
I added the map function 12 hours ago, I just need the pull request to be accepted

**Comment by WildJimmy** [comment]
Just accepted all merge requests from last night, so the code should be up to date
