### ISSUE TITLE
Documentation of Unit Test

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework3G3#47]
@s4il3sh do you need to do documentation of the unit test or just the algorithm itself? If you'd like to include the unit test I can make sure that's finished tonight so you have enough time, just let me know. I don't think it's necessary so it should be a matter of preference

**Comment by s4il3sh** [comment]
Let's keep the unit test file different. I am going to put the introduction, process, and results with our code inside the documentation. Is that okay?

**Comment by s4il3sh** [comment]
Also, I see the unit test code is different than our main code. They should be the same, right?

**Comment by WildJimmy** [comment]
Discussed in #67, everything is now compatible so closing the issue
