### ISSUE TITLE
Other Functionality of the Algorithm

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework3G3#48]
Hi All,

Are we just calculating the spring constant, or are we also going to plot motion (or other things?) I know we mentioned that as a possibility earlier, but given the amount of time we have left I just wanted to check so I know what to be looking for in my unit test

**Comment by s4il3sh** [comment]
well, we need a best-fit line from the data provided and determine its slope using the equation m = k/g * x, where k/g is a slope from the line. After obtaining the slope we find k. How about we do that? Also if possible make a graph of it.

**Comment by reshnashrestha** [comment]
I looked at your works and it seems lesser compared to other groups better you add something.
