### ISSUE TITLE
We should create a milestone

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework3G3#5]
I think we should create a milestone for "Getting Started" or something like that. Inside we would have the issues pertaining to deciding maintainer, distributing our tasks, and which topic we should cover. I understand these issues are already completed but I think its good practice (and good for grading of course). Unfortunately, I believe only the maintainer can do that. So, @WildJimmy could you do that when the professor assigns you that role?

**Comment by s4il3sh** [comment]
Yep! We need to make a road map of what we are going to do. Let's plan about it. Well,
create a milestone for the following things:
- license
- algorithm
- unit-test
- documentation
And you may add other things in between whatever tasks need to be created.

**Comment by WildJimmy** [comment]
Created milestone 1 (Distributing Work) and assigned this to it
