### ISSUE TITLE
Clarification needed. 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework3G3#55]
Hello, As, per my knowledge, the unit test is something, to check whether the code is correct or not, The unit test code, is a different code which checks the original code right?. To me more precise, should it be the same code and checking for different inputs, or it should be a different code?
Thank you,

**Comment by WildJimmy** [comment]
Hi Arif,

The unit test should be a separate file which checks the output of your algorithm. It is separate code that goes through different inputs for your original algorithm and checks them for accuracy if that makes sense

**Comment by uarif** [comment]
> Hi Arif,
> 
> The unit test should be a separate file which checks the output of your algorithm. It is separate code that goes through different inputs for your original algorithm and checks them for accuracy if that makes sense

Yes, that is exactly what my understanding was, but the other person in our group has some other explanation. Anyway, thank you very much for the clarification.

**Comment by poojashresthacode** [comment]
Oh, but I used to think that we had to make a separate file for the unit test using the same code and just the inputs are different. Is it not that?? I am so confused now.
