### ISSUE TITLE
Parameter Cases for Unit Test

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework3G3#58]
Is there anything else I can test for the unit test other than a few different masses and extensions? There also should be edge cases for negative m, negative extension, and 0 for both as well, but is there anything else I'm missing?

**Comment by s4il3sh** [comment]
I guess that's it. Don't we have to go line by line unit-test for our code?

**Comment by JustinJaniszewski** [comment]
I do not think it is required unless you want to. We can just state (maybe in documentation) the bounds of our algorithm. As in, a negative mass, zero mass, or negative extention do not make sense.  

However, you could do an assert statement which would stop the code and give in error in the console if it is "out of bounds" so to speak. If you would like help with this, let me know.

**Comment by s4il3sh** [comment]
Also, @WildJimmy check our code once and our unit test should be based on our code, right?

**Comment by WildJimmy** [comment]
Yep, unit test is finished and all looks well. Closing this issue
