### ISSUE TITLE
Finalize our work

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework3G3#60]
Guys do check our documentation, unit-test, code, docstring, and license and give a final output.

**Comment by WildJimmy** [comment]
@s4il3sh yep, now that the algorithm is finished I'll be changing the unit test just a bit to properly reflect the finished code. Will be merged soon

**Comment by WildJimmy** [comment]
Seems we've finalized everything with (https://github.com/ubsuny/23-Homework3G3/pull/73), closing this
