### ISSUE TITLE
Avoid using units of "dynes"

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework3G3#63]
In the code the results are given in dynes. I think it is best if we stick with Newtons. It makes the code easier to read for the group members and other classmates.

**Comment by s4il3sh** [comment]
Well, it's written in CGS system since we have used mass in gram, length in cm and time in seconds. But it's not a big deal we can convert it to Newtone multiplying by factor 10^-5.

**Comment by JustinJaniszewski** [comment]
If you could either convert or state what a dyne is in documentation or something that would be great

**Comment by s4il3sh** [comment]
Yes, thank you for your suggestion. I have converted it into N/m. Please check or make commit accordingly if necessary.

**Comment by JustinJaniszewski** [comment]
Sounds good to me, thank you.
