### ISSUE TITLE
 Help needed to resolve the issue of Group2

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework3G3#68]
We uploaded a new file that contains some changes. However, we found the following error after merging with the main repository.

![Screenshot from 2023-10-06 09-58-24](https://github.com/ubsuny/23-Homework3G3/assets/66480280/7b7730e2-04f4-41c4-85e6-8bc67d5ad5a8)

**Comment by yasmensarhan27** [comment]
copy the code you have done on google Colab and paste it in a new python file in your repository

**Comment by AhmedCode99** [comment]
colab issue, save your colab notebook as a file in git

**Comment by Mosaddeq107** [comment]
Thank you for your suggestion. We solved it.
