### ISSUE TITLE
Adjustments from Professor

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework3G3#69]
Hi @s4il3sh,

I see that you've been discussing changes with the professor on your newest merge request. Should I wait to merge that or should I just do it now and you'll make another one if you make those changes before the deadline? No worries either way, just let me know if I should hold off or not

**Comment by s4il3sh** [comment]
Yes. changes are made. You are good to go. just accept the merge request and your unit-test will work too. Btw, remove the file .ipynb file which does not give our final output.

**Comment by WildJimmy** [comment]
Sounds good, thanks! I will probably remove that notebook, but I wanted to accept the request so as to not keep that student from receiving credit for making changes that (at least at the time) were meaningful
