### ISSUE TITLE
Error: matplotlib does not support generators as input

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework3G3#78]
I generated a list using map(), but now I can't plot it

**Comment by Mosaddeq107** [comment]
You can use these codes

#Sample data
numbers = [1, 2, 3, 4, 5]

#Use map() to square the numbers
squared_numbers = list(map(lambda x: x**2, numbers))

**Comment by AhmedCode99** [comment]
https://stackoverflow.com/questions/56904450/runtimeerror-matplotlib-does-not-support-generators-as-input
